database:
  url: 192.168.0.221:1433
  username: itapsa
  password: Andr0m3d4

spring:
  application:
    name: Face
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServer2008Dialect
jasypt:
  encryptor:
    password: http://192.168.0.245/authorization/oauth2/jwks
server:
  port: 8083
  servlet:
    context-path: /face-api